###
# Model Configuration: LLaMA-3 8B
###

base_model: NousResearch/Meta-Llama-3-8B
model_type: AutoModelForCausalLM
tokenizer_type: AutoTokenizer

sequence_len: 4096

# base model weight quantization
load_in_8bit: true

# attention implementation
flash_attention: true

# finetuned adapter config
adapter: lora
lora_model_dir:
lora_r: 16
lora_alpha: 32
lora_dropout: 0.05
lora_target_linear: true
lora_fan_in_fan_out:
lora_modules_to_save: # required when adding new tokens to LLaMA/Mistral
    - embed_tokens
    - lm_head
# for details, see https://github.com/huggingface/peft/issues/334#issuecomment-1561727994

# Use OpenAI format (copied from https://github.com/fozziethebeat/axolotl/blob/main/examples/llama-3/instruct-lora-8b.yml)
chat_template: llama3
datasets:
    - path: data.jsonl
      type: chat_template
      chat_template: llama3
      field_messages: messages
      message_field_role: role
      message_field_content: content
      roles:
          system:
              - system
          user:
              - user
          assistant:
              - assistant

special_tokens:
    bos_token: '<|begin_of_text|>'
    eos_token: '<|eot_id|>'
    pad_token: '<|end_of_text|>'

tokens:
    - '<|start_header_id|>'
    - '<|end_header_id|>'
    - <|eom_id|>
    - <|eot_id|>
    - <|python_tag|>
    - <|finetune_right_pad_id|>

# Set aside this ratio of samples for training evaluation
val_set_size: 0.1

###
# Training Configuration
###

train_on_inputs: false
group_by_length: false

# random seed for better reproducibility
seed: 117

# optimizer config
optimizer: adamw_bnb_8bit
learning_rate: 0.0001
lr_scheduler: cosine
num_epochs: 15
micro_batch_size: 8
gradient_accumulation_steps: 1
warmup_steps: 10

# axolotl saving config
dataset_prepared_path: last_run_prepared
output_dir: ./lora-out

# logging and eval config
logging_steps: 1
evals_per_epoch: 4

# training performance optimization config
bf16: auto
tf32: false
gradient_checkpointing: true

###
# Miscellaneous Configuration
###

# when true, prevents over-writing the config from the CLI
strict: false

# "Don't mess with this, it's here for accelerate and torchrun" -- axolotl docs
local_rank:
